export const HCI = {
  VM: 'kubevirt.io.virtualmachine',
  VMI: 'kubevirt.io.virtualmachineinstance',
  VMIM: 'kubevirt.io.virtualmachineinstancemigration',
  VM_TEMPLATE: 'zeushci.io.virtualmachinetemplate',
  VM_VERSION: 'zeushci.io.virtualmachinetemplateversion',
  IMAGE: 'zeushci.io.virtualmachineimage',
  SSH: 'zeushci.io.keypair',
  VOLUME: 'zeushci.io.volume',
  USER: 'zeushci.io.user',
  SETTING: 'zeushci.io.setting',
  UPGRADE: 'zeushci.io.upgrade',
  UPGRADE_LOG: 'zeushci.io.upgradelog',
  SCHEDULE_VM_BACKUP: 'zeushci.io.schedulevmbackup',
  BACKUP: 'zeushci.io.virtualmachinebackup',
  RESTORE: 'zeushci.io.virtualmachinerestore',
  NODE_NETWORK: 'network.zeushci.io.nodenetwork',
  CLUSTER_NETWORK: 'network.zeushci.io.clusternetwork',
  SUBNET: 'kubeovn.io.subnet',
  VPC: 'kubeovn.io.vpc',
  VM_IMAGE_DOWNLOADER: 'zeushci.io.virtualmachineimagedownloader',
  SUPPORT_BUNDLE: 'zeushci.io.supportbundle',
  NETWORK_ATTACHMENT: 'zeushci.io.networkattachmentdefinition',
  CLUSTER: 'zeushci.io.management.cluster',
  DASHBOARD: 'zeushci.io.dashboard',
  BLOCK_DEVICE: 'zeushci.io.blockdevice',
  CLOUD_TEMPLATE: 'zeushci.io.cloudtemplate',
  HOST: 'zeushci.io.host',
  VERSION: 'zeushci.io.version',
  SNAPSHOT: 'zeushci.io.volumesnapshot',
  VM_SNAPSHOT: 'zeushci.io.vmsnapshot',
  ALERTMANAGERCONFIG: 'zeushci.io.monitoring.alertmanagerconfig',
  CLUSTER_FLOW: 'zeushci.io.logging.clusterflow',
  CLUSTER_OUTPUT: 'zeushci.io.logging.clusteroutput',
  FLOW: 'zeushci.io.logging.flow',
  OUTPUT: 'zeushci.io.logging.output',
  STORAGE: 'zeushci.io.storage',
  RESOURCE_QUOTA: 'zeushci.io.resourcequota',
  KSTUNED: 'node.zeushci.io.ksmtuned',
  HUGEPAGES: 'node.zeushci.io.hugepage',
  PCI_DEVICE: 'devices.zeushci.io.pcidevice',
  PCI_CLAIM: 'devices.zeushci.io.pcideviceclaim',
  SR_IOV: 'devices.zeushci.io.sriovnetworkdevice',
  VGPU_DEVICE: 'devices.zeushci.io.vgpudevice',
  SR_IOVGPU_DEVICE: 'devices.zeushci.io.sriovgpudevice',
  USB_DEVICE: 'devices.zeushci.io.usbdevice',
  USB_CLAIM: 'devices.zeushci.io.usbdeviceclaim',
  MIG_CONFIGURATION: 'devices.zeushci.io.migconfiguration',
  VLAN_CONFIG: 'network.zeushci.io.vlanconfig',
  VLAN_STATUS: 'network.zeushci.io.vlanstatus',
  ADD_ONS: 'zeushci.io.addon',
  LINK_MONITOR: 'network.zeushci.io.linkmonitor',
  SECRET: 'zeushci.io.secret',
  INVENTORY: 'metal.zeushci.io.inventory',
  LB: 'loadbalancer.zeushci.io.loadbalancer',
  IP_POOL: 'loadbalancer.zeushci.io.ippool',
  HARVESTER_CONFIG: 'rke-machine-config.cattle.io.harvesterconfig',
  LVM_VOLUME_GROUP: 'zeushci.io.lvmvolumegroup',
  VMIMPORT_SOURCE_V: 'migration.zeushci.io.vmwaresource',
  VMIMPORT_SOURCE_O: 'migration.zeushci.io.openstacksource',
  VMIMPORT_SOURCE_OVA: 'migration.zeushci.io.ovasource',
  VMIMPORT: 'migration.zeushci.io.virtualmachineimport',
  MIGRATION: 'migration.zeushci.io',
};

export const VOLUME_SNAPSHOT = 'snapshot.storage.k8s.io.volumesnapshot';
export const CSI_DRIVER = 'storage.k8s.io.csidriver';
export const VOLUME_SNAPSHOT_CLASS = 'snapshot.storage.k8s.io.volumesnapshotclass';
